### ISSUE TITLE
benchmark does not  work in firefox

### ISSUE THREAD

**Issue by dotnetCarpenter** [mgold/Benchmark-Visualization#1]
I just tried to run bench mark code in FF42 and I got errors as soon as I moused over the graphs.

```
ReferenceError: legend is not defined
http://localhost:8000/benchmarks.js
Line 135
```

[Line 135](https://github.com/mgold/Benchmark-Visualization/blob/db8b80130b07aff23229dad0a150d0197813324c/benchmarks.js#L136) has a reference to the `legend` function defined one line below. `legend` should clearly be hoist so the reference is valid. I then open the same page in nightly, to see if this had been fixed in FF44.0a2 (2015-12-01) but no. Just to be sure, I loaded the same page in Chrome and Internet Explorer - both works.

This is clearly a bug in FF but I will leave this issue here as this project is directly affected and so I can reference this issue later in bugzilla.

Adding the `"use strict";` pragma gave some insights. _SyntaxError: in strict mode code, functions may be declared only at top level or immediately within another function_
Hence, moving `legend` outside the if body fixed the issue in FF.

**Comment by dotnetCarpenter** [comment]
Filed bug in bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1229998

**Comment by bzbarsky** [comment]
> legend should clearly be hoist 

Sort of clearly.  Up until ES 2016 this year, this sort of thing wasn't even valid JavaScript.  See http://www.ecma-international.org/ecma-262/6.0/#sec-block-level-function-declarations-web-legacy-compatibility-semantics for the gory details.

**Comment by bzbarsky** [comment]
But in the meantime, moving the declaration of `legend` outside the `if` body, or to above its uses inside the `if` body, would make this code work in all existing browsers.

**Comment by dotnetCarpenter** [comment]
@bzbarsky thanks for the link. After 8 years of using js a main language, I'm still learning new intricate secrets. :dancer:

**Comment by mgold** [comment]
Thanks everyone! Fix should be merged. I need to put the essay on my new site and give this old code another look over.
